#!/usr/bin/env python
#
#    Cardapio is an alternative menu applet, launcher, and much more!
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import mateapplet
import os

from matepanel.CardapioMateAppletFactory import CardapioMateAppletFactory

# make sure Cardapio shows even if using Ubuntu's AppMenu
os.environ['UBUNTU_MENUPROXY'] = ''

mateapplet.matecomponent_factory('OAFIID:MATE_Cardapio_Factory',
		mateapplet.Applet.__gtype__, 'Cardapio', '0', CardapioMateAppletFactory)


